canny_threshold: 70

# coordinates of the point, which will be backprojected to the camera image from the specified frame
world_frame_id: "gps_origin"
world_point:
  x: 0.0
  y: 0.0
  z: 0.0

rate:
  # how often to publish my topic?
  publish: 10 # [Hz]
  # how often check whether msgs are arriving?
  check_subscribers: 1 # [Hz]

